// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// msgid
type EUserMsg int32

const (
	EUserMsg_ID_SysBusy  EUserMsg = 2
	EUserMsg_ID_LoadUser EUserMsg = 1001
)

var EUserMsg_name = map[int32]string{
	2:    "ID_SysBusy",
	1001: "ID_LoadUser",
}
var EUserMsg_value = map[string]int32{
	"ID_SysBusy":  2,
	"ID_LoadUser": 1001,
}

func (x EUserMsg) Enum() *EUserMsg {
	p := new(EUserMsg)
	*p = x
	return p
}
func (x EUserMsg) String() string {
	return proto.EnumName(EUserMsg_name, int32(x))
}
func (x *EUserMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EUserMsg_value, data, "EUserMsg")
	if err != nil {
		return err
	}
	*x = EUserMsg(value)
	return nil
}
func (EUserMsg) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

//
type LoadUserReq struct {
	UserId           *int64 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoadUserReq) Reset()                    { *m = LoadUserReq{} }
func (m *LoadUserReq) String() string            { return proto.CompactTextString(m) }
func (*LoadUserReq) ProtoMessage()               {}
func (*LoadUserReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *LoadUserReq) GetUserId() int64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type LoadUserResp struct {
	UserId           *int64  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	UserName         *string `protobuf:"bytes,2,req,name=user_name,json=userName" json:"user_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoadUserResp) Reset()                    { *m = LoadUserResp{} }
func (m *LoadUserResp) String() string            { return proto.CompactTextString(m) }
func (*LoadUserResp) ProtoMessage()               {}
func (*LoadUserResp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *LoadUserResp) GetUserId() int64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *LoadUserResp) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func init() {
	proto.RegisterType((*LoadUserReq)(nil), "msg.LoadUserReq")
	proto.RegisterType((*LoadUserResp)(nil), "msg.LoadUserResp")
	proto.RegisterEnum("msg.EUserMsg", EUserMsg_name, EUserMsg_value)
}

func init() { proto.RegisterFile("user.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x52, 0xe3, 0xe2, 0xf6,
	0xc9, 0x4f, 0x4c, 0x09, 0x2d, 0x4e, 0x2d, 0x0a, 0x4a, 0x2d, 0x14, 0x12, 0xe7, 0x62, 0x07, 0xa9,
	0x88, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd2, 0x60, 0x0e, 0x62, 0x03, 0x71, 0x3d, 0x53, 0x94,
	0x5c, 0xb8, 0x78, 0x10, 0xea, 0x8a, 0x0b, 0x70, 0x2a, 0x14, 0x92, 0xe6, 0xe2, 0x04, 0x4b, 0xe4,
	0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x69, 0x70, 0x06, 0x71, 0x80, 0x04, 0xfc, 0x12, 0x73,
	0x53, 0xb5, 0x74, 0xb8, 0x38, 0x5c, 0x41, 0x46, 0xf8, 0x16, 0xa7, 0x0b, 0xf1, 0x71, 0x71, 0x79,
	0xba, 0xc4, 0x07, 0x57, 0x16, 0x3b, 0x95, 0x16, 0x57, 0x0a, 0x30, 0x09, 0x09, 0x70, 0x71, 0x7b,
	0xba, 0xc4, 0xc3, 0x2c, 0x11, 0x78, 0xc9, 0x0e, 0x08, 0x00, 0x00, 0xff, 0xff, 0x63, 0xcf, 0x7f,
	0x8f, 0xad, 0x00, 0x00, 0x00,
}
